### ISSUE TITLE
Connecting with non admin user to influxdb from kapacitor

### ISSUE THREAD

**Issue by timkoopmans** [influxdata/kapacitor#962] opened 2016-10-10 03:26 UTC
Hi,

Given a non admin user in influxdb:

```
> create user test with password 'abcd'
> grant write on "results" to "test"
> show grants for "test"
database    privilege
results     WRITE
```

It does not seem possible to connect to influxdb from kapacitor with this non admin user. The following error is presented:

```
KAPACITOR_INFLUXDB_0_USERNAME=test \
KAPACITOR_INFLUXDB_0_PASSWORD=abcd \
KAPACITOR_INFLUXDB_0_URLS_0=https://test.influxcloud.net:8086/ \
kapacitord -config config/kapacitor.conf

...
[task_master:main] 2016/10/10 14:21:55 I! closed
[run] 2016/10/10 14:21:55 E! open server: open service *influxdb.Service: error authorizing query: test not authorized to execute statement 'SHOW DATABASES'
run: open server: open service *influxdb.Service: error authorizing query: test not authorized to execute statement 'SHOW DATABASES'
```

Advice [here (Allow a non-admin user to USE DATABASE in the CLI)](https://www.influxdata.com/tldr-influxdb-tech-tips-april-21-2016/) suggests specifying a database parameter (in the CLI) to avoid the `SHOW DATABASES`  command but I'm not sure how we can avoid that when using kapacitor.

**Comment by phemmer** [comment] 2016-10-10 04:02
See also https://github.com/influxdata/influxdb/issues/4785

**Comment by nathanielc** [comment] 2016-10-11 15:50
@90kts:  @phemmer Is correct the user with which Kapacitor connects to InfluxDB needs to be able to run:

* SHOW DATABASES
* SHOW SUBSCRIPTIONS
* CREATE/DROP  SUBSCRIPTION
* SELECT ....

If you disable subscriptions then only SELECT queries will be needed.

The management of subscriptions is considered an admin level permission.

**Comment by 90kts** [comment] 2016-10-11 21:07
OK so I guess my issue is more around have 'write only' privs for kapacitor into influx. Doesn't seem like it's possilbe without giving the kapacitor user admin privs. Happy to close this issue if that is intended behaviour.

**Comment by nathanielc** [comment] 2016-10-11 21:15
@90kts It possible to use Kapacitor with a write only InfluxDB user. Kapacitor doesn't explicitly check permissions so if you only use the subset of features Kapacitor provides that don't require the admin priv, then a write only user should work.

Specifically you would need to:

* Setup subscriptions by hand and disable subscriptions in the Kapacitor config(this way Kapacitor doesn't try to mamage them).  Alertnatively send data to Kapacitor via some other means.
* Not use batch tasks as they naturally query data from InfluxDB

**Comment by 90kts** [comment] 2016-10-11 22:06
OK great thanks, I understand now what you mean by managing subscriptions.

**Closed** 2022-11-10 02:31 UTC
