### ISSUE TITLE
Not respecting custom config and error: subscription already exists

### ISSUE THREAD

**Issue by JeremyCraven** [influxdata/kapacitor#653] opened 2016-06-17 20:42 UTC
We are using the supported kapacitor docker image and copying our custom config file into the image.  However, when running kapacitor, our config is ignored and instead kapacitor tries to connect to localhost instead of our specified influx instance.  Here is our Dockerfile and config.

Dockerfile

```
FROM kapacitor:0.13.1

MAINTAINER Geofeedia <https://geofeedia.com>

COPY kapacitor.conf /etc/kapacitor/kapacitor.conf
```

kapacitor.conf

```
# The hostname of this node.
# Must be resolvable by any configured InfluxDB hosts.
hostname = "127.0.0.1"
# Directory for storing a small amount of metadata about the server.
data_dir = "/var/lib/kapacitor"

# Multiple InfluxDB configurations can be defined.
# Exactly one must be marked as the default.
# Each one will be given a name and can be referenced in batch queries and InfluxDBOut nodes.
[[influxdb]]
  # Connect to an InfluxDB cluster
  # Kapacitor can subscribe, query and write to this cluster.
  # Using InfluxDB is not required and can be disabled.
  enabled = true
  default = true
  name = "geo-influx"
  urls = ["http://10.240.0.37:8086"]
  username = ""
  password = ""
  timeout = 0
  # Absolute path to pem encoded CA file.
  # A CA can be provided without a key/cert pair
  #   ssl-ca = "/etc/kapacitor/ca.pem"
  # Absolutes paths to pem encoded key and cert files.
  #   ssl-cert = "/etc/kapacitor/cert.pem"
  #   ssl-key = "/etc/kapacitor/key.pem"

  # Do not verify the TLS/SSL certificate.
  # This is insecure.
  insecure-skip-verify = false

  # Maximum time to try and connect to InfluxDB during startup
  startup-timeout = "20s"

  # Turn off all subscriptions
  disable-subscriptions = false

  # Which protocol to use for subscriptions
  # one of 'udp', 'http', or 'https'.
  subscription-protocol = "http"

  # Subscriptions resync time interval
  # Useful if you want to subscribe to new created databases
  # without restart Kapacitord
  subscriptions-sync-interval = "1m0s"

  # Host part of a bind addres for UDP listeners.
  # For example if a UDP listener is using port 1234
  # and `udp-bind = "hostname_or_ip"`,
  # then the UDP port will be bound to `hostname_or_ip:1234`
  # The default empty value will bind to all addresses.
  udp-bind = ""
  # Subscriptions use the UDP network protocl.
  # The following options of for the created UDP listeners for each subscription.
  # Number of packets to buffer when reading packets off the socket.
  udp-buffer = 1000
  # The size in bytes of the OS read buffer for the UDP socket.
  # A value of 0 indicates use the OS default.
  udp-read-buffer = 0

  [influxdb.subscriptions]
    # Set of databases and retention policies to subscribe to.
    # If empty will subscribe to all, minus the list in
    # influxdb.excluded-subscriptions
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]

  [influxdb.excluded-subscriptions]
    # Set of databases and retention policies to exclude from the subscriptions.
    # If influxdb.subscriptions is empty it will subscribe to all
    # except databases listed here.
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
```

[srv] 2016/06/17 20:39:01 E! error closing service *stats.Service: error closing stats service: service not open
[httpd] 2016/06/17 20:39:01 I! Closed HTTP service
[task_master] 2016/06/17 20:39:01 I! closed
[run] 2016/06/17 20:39:01 E! open server: open service *influxdb.Service: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
run: open server: open service *influxdb.Service: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused

**Comment by nathanielc** [comment] 2016-06-17 20:46
@JeremyCraven Looks like the default image doesn't pass the `-config` flag so its always running with the defaults (overridden by any env vars) . In order to pick up your config change the CMD to have the `-config` flag.

For example:
```
FROM kapacitor:0.13.1

MAINTAINER Geofeedia <https://geofeedia.com>

COPY kapacitor.conf /etc/kapacitor/kapacitor.conf

CMD ["kapacitord", "-config", "/etc/kapacitor/kapacitor.conf"]
```

That should do it.

**Comment by JeremyCraven** [comment] 2016-06-20 12:38
Thanks for your help.  Tried that and Kapacitor is definitely reading our config, but now we are getting a new error.  We tried dropping subscriptions, but everytime Kapacitor is started we get this.

```
'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2016/06/20 12:31:53 Using configuration at: /etc/kapacitor/kapacitor.conf
run: open server: open service *influxdb.Service: subscription already exists
```

**Comment by rossmcdonald** [comment] 2016-06-20 15:50
@JeremyCraven It sounds like your Kapacitor data directory is getting wiped on restart. Are you mounting it when running the container?

**Comment by JeremyCraven** [comment] 2016-06-20 17:43
We are mounting var/lib/kapacitor on a google cloud persistent disk is there somewhere else that should be mounted?

**Comment by rossmcdonald** [comment] 2016-06-20 17:52
@JeremyCraven No, as long as it is being persisted (and read back on service start) then I don't think you should see any issues. The `subscription already exists` error makes me think that the boltdb database (stored in `/var/lib/kapacitor`) is not being persisted correctly and is being recreated on every service start. It's definitely a bug that Kapacitor can't start if the subscriptions already exist, though.

If you restart the service, are all of your tasks still defined correctly?

**Comment by JeremyCraven** [comment] 2016-06-20 18:35
After restarting the service all my tasks are still defined correctly.  As of now, if I need to restart Kapacitor I can manually drop all subscriptions and then restart and it works fine.

**Comment by JeremyCraven** [comment] 2016-06-21 19:31
Just wondering what the timeline is on fixing that subscription already exists bug.  I could always fix it and create a PR if it's not a large undertaking.

**Comment by nathanielc** [comment] 2016-06-28 22:31
@JeremyCraven The subscription issue has been reported here https://github.com/influxdata/kapacitor/issues/679

Can you add your details to that issue since I am unable to reproduce locally?

Closing this issue as we can track the subscription issue in #679

**Closed by nathanielc** 2016-06-28 22:31 UTC
Labels: bug
