### ISSUE TITLE
.quiet() Doesn't Work in influxDBOut Node: "Missing Value From Point"

### ISSUE THREAD

**Issue by mertbakir** [influxdata/kapacitor#2371] opened 2020-07-21 17:42 UTC
I've actually opened a thread in [community](https://community.influxdata.com/t/kapacitor-missing-from-point-errors/15338) yet I thought it's OK to ask here too since this looks like a bug (?)

Hi, I've created a very simple TICKScript. Even though, it works as expected and writes data back to influxdb, it still returns these errors.

```
ts=2020-07-21T20:25:26.714+03:00 lvl=error msg="failed to realize reduce context from fields" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="field \"http_response_code\" missing from point"
ts=2020-07-21T20:26:22.787+03:00 lvl=error msg="failed to aggregate point in batch" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="field http_response_code missing from point cannot aggregate"
ts=2020-07-21T20:26:22.788+03:00 lvl=error msg="error while evaluating expression" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="left reference value \"status_code\" is missing value"
ts=2020-07-21T20:27:03.255+03:00 lvl=error msg="error while evaluating expression" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="left reference value \"status_code\" is missing value"
ts=2020-07-21T20:27:03.255+03:00 lvl=error msg="failed to realize reduce context from fields" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="field \"http_response_code\" missing from point"
ts=2020-07-21T20:27:46.283+03:00 lvl=error msg="error while evaluating expression" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="left reference value \"status_code\" is missing value"
ts=2020-07-21T20:27:46.284+03:00 lvl=error msg="failed to aggregate point in batch" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="field http_response_code missing from point cannot aggregate"
ts=2020-07-21T20:27:53.419+03:00 lvl=error msg="failed to realize reduce context from fields" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="field \"http_response_code\" missing from point"
ts=2020-07-21T20:27:53.420+03:00 lvl=error msg="error while evaluating expression" service=kapacitor task_master=main task=TRANSFORM_HTTP_2 node=influxdb_out11 err="left reference value \"status_code\" is missing value"
```

I collect data using telegraf's http_response plugin.

```
var measurement = 'http_response'
...
var groupBy = ['name', 'server', 'site']
var whereFilterSuccess = lambda: ("status_code" == '200' AND "result" == 'success')
...
var outputDB = 'kapacitor_debugging'
var outputRP = 'autogen'
var outputMeasurement = 'X001'
...
var window_size = 1m
var id = '{{ .TaskName }}:{{ .Name }}:{{ .Group }}'

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |window()
        .period(window_size)
        .every(window_size)
        .align()

var total = data
    |count('http_response_code')
        .as('counter')

var success = data
    |where(whereFilterSuccess)
    |count('http_response_code')
        .as('counter')

var availability = total
    |join(success)
        .as('total', 'success')
        .fill('null')
    |eval(lambda: "total.counter", lambda: "success.counter", lambda: float("success.counter") / float("total.counter"))
        .as('total', 'success', 'rate')
        .keep('total', 'success', 'rate')
    |log()
        .prefix('A021')
    |influxDBOut()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .precision('s')
        .quiet()
```

It says that errors are coming from influxdb_out node even though I've used the option ```.quiet()```. I don't need the ```http_response_code``` or ```status_code```. I've what I need in ```|log()``` and it writes to influxDB as expected. Yet there are errors.

**Comment by docmerlin** [comment] 2020-08-03 18:33
These need to check if the node `IsQuiet`.

https://github.com/influxdata/kapacitor/blob/ea9612a26271bc9ed45e1dbe3d188e41337e05c1/influxdb_out.go#L268

https://github.com/influxdata/kapacitor/blob/ea9612a26271bc9ed45e1dbe3d188e41337e05c1/influxdb_out.go#L278

https://github.com/influxdata/kapacitor/blob/ea9612a26271bc9ed45e1dbe3d188e41337e05c1/influxdb_out.go#L299

**Comment by danxmoran** [comment] 2020-11-02 14:48
Hi @mertbakir, apologies for the long delay. I spent some time digging into this and I think at least one bug is in kapacitor's logic for tracking node context, because the message `"error while evaluating expression"` doesn't appear in the implementation of `influxDBOut` nodes, but it _does_ appear in the code for `where` nodes. As a work-around, does adding `.quiet()` to your `|where` nodes help reduce the noise?

I haven't been able to reproduce the error locally yet. What version of kapacitor are you running? Are there any meaningful details left out (replaced by the `...`s) of the example script you posted when filing the issue?

**Comment by danxmoran** [comment] 2020-11-30 20:48
Closing for now since we can't reproduce the context-tracking bug

**Closed by danxmoran** 2020-11-30 20:48 UTC
Labels: bug, needs more info
