### ISSUE TITLE
Get the newest point instead of the oldest point in a batch alert.

### ISSUE THREAD

**Issue by titilambert** [influxdata/kapacitor#1010] opened 2016-11-01 19:22 UTC
Here my TICK file
```    batch
        |query('''SELECT gauge, namespace_name, deployment
               FROM "k8s"."default".kube_deployment_status_replicas_unavailable
            ''')
            .groupBy('namespace_name', 'deployment')
            .period(3m)
            .every(1m)
            .fill(0)
        |alert()
            .id('{{ index .Tags "namespace_name" }}/deployment/{{ index .Tags "deployment" }}/unavailable')
            .message('Time: {{ .Time }}
    # Level: {{ .Level }}
    # Object: {{ .ID }}
    # Unavailable replicas: {{ index .Fields "gauge" }}')
                .all()
            .crit(lambda: "gauge" > 0)
            .stateChangesOnly()
            .slack()
            .channel('#alerts-k8s')
```

This works correctly. It  checks every 1 min for "gauge > 0" on each points on last 3 min to generate an alert and when we got 1 point with gauge = 0, I got the recovery alert.

The issue, is in the message {{ index .Fields "gauge" }} takes the value of the first point (the oldest point) of the 3 min window ...
So I got "# Unavailable replicas: 6 " But it should be "# Unavailable replicas: 0", 0 being the value of the newest point

**Comment by nathanielc** [comment] 2016-12-21 17:23
In summary you are doing two things:

1. Checking that all points in the last 3m have a `gauge > 0`
2. You want to report the value of the last point in the alert message.

If you separate out those parts and join them back together it will work:

Something like this:

```
var data = batch
        |query('''SELECT gauge, namespace_name, deployment
               FROM "k8s"."default".kube_deployment_status_replicas_unavailable
            ''')
            .groupBy('namespace_name', 'deployment')
            .period(3m)
            .every(1m)
            .fill(0)

var last = data
    |last('gauge')
        .as('gague') 

var min = data
    |min('gauge')
         .as('gauge')

last
    |join(min)
        .as('last','min')
    |alert()
            .id('{{ index .Tags "namespace_name" }}/deployment/{{ index .Tags "deployment" }}/unavailable')
            .message('Time: {{ .Time }}
    # Level: {{ .Level }}
    # Object: {{ .ID }}
    # Unavailable replicas: {{ index .Fields "last.gauge" }}')
            .crit(lambda: "min.gauge" > 0)
            .stateChangesOnly()
            .slack()
            .channel('#alerts-k8s')
```

**Comment by djsly** [comment] 2016-12-21 18:43
Thanks this works!

do you want to keep this Ticket open to have a cleaner fix or this is by design ? 

I will be converting all of our tick script that are using batch Node and will update if I find any use cases that this solution doesn't cover

**Comment by nathanielc** [comment] 2016-12-21 19:45
@djsly Thanks! I'll close it.

**Closed by nathanielc** 2016-12-21 19:45 UTC
