### ISSUE TITLE
Allow ENV configuration to not just override existing sections but to add new entries to a slice.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/kapacitor#1398] opened 2017-05-23 16:59 UTC
Current the ENV configuration is not ideal since you have to have a dummy place holder section for all slice based config sections in order to be able to set the configuration via the ENV. It would be best if the ENV could control the configuration regardless of the contents of the configuration file.

**Comment by desa** [comment] 2017-05-24 18:30
duplicate of https://github.com/influxdata/kapacitor/issues/1344

**Closed by desa** 2017-05-24 18:30 UTC
