### ISSUE TITLE
Message field in Alert Rule Builder not accepting correct code

### ISSUE THREAD

**Issue by steenstra** [influxdata/kapacitor#2238] opened 2019-08-19 13:34 UTC
I get the following message: 
`Please correct templates in alert message`

for this code:
`{{.Tags.host}} drive {{.Tags.instance}} Free Disk space is: {{ index .Fields "value" | printf "%0.2f"}}%`

When I add the code directly in the Message variable in the script, this works as intended and gives the following result:
`DB04 drive F: Free Disk space is: 6.94%`

When I edit the Scipt via the alert rule builder, I am unable to save the changes because it thinks the syntax is incorrect. 

My full code is:

```

var db = 'telegraf'

var rp = 'autogen'

var measurement = 'win_disk'

var groupBy = ['host', 'instance']

var whereFilter = lambda: ("instance" == 'C:' OR "instance" == 'D:' OR "instance" == 'E:' OR "instance" == 'F:' OR "instance" == 'G:')

var name = 'Diskusage'

var idVar = name + '-{{.Group}}'

var message = '{{.Tags.host}} drive {{.Tags.instance}} Free Disk space is: {{ index .Fields "value" | printf "%0.2f"}}%'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 10

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "Percent_Free_Space")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .slack()
        .channel('#alerting')
        .username('Kapacitor')
        .iconEmoji(':thinking_face:')

trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')

```

**Comment by eras** [comment] 2022-10-11 06:34
I have the same problem, but the issue is in ChronoGraf, not Kapacitor:

https://github.com/influxdata/chronograf/blob/406065e391633812d378fd644cb2ef8922020dfd/ui/src/kapacitor/utils/alertMessageValidation.ts#L63

I suppose the workaround is to start using TICK scripts. There's a fix at https://github.com/influxdata/chronograf/issues/5343 so maybe a more version of ChronoGraf fixes it for you.

I suggest closing this issue and submitting one in ChronoGraf if the issue still persists.

**Closed** 2022-11-01 05:57 UTC
