### ISSUE TITLE
HttpPost headers don't work when added via environment variables

### ISSUE THREAD

**Issue by petetnt** [influxdata/kapacitor#2280] opened 2020-01-21 13:28 UTC
In Kapacitor 1.5.*, The documentation mentions in multiple points that HTTPPost node headers could be set via enviroment variables. For example:

https://docs.influxdata.com/kapacitor/v1.5/event_handlers/post/#defining-configuration-options-with-environment-variables

> The endpoint, url, and headers configuration options can be defined with environment variables:
>
> KAPACITOR_HTTPPOST_0_ENDPOINT = "example"
> KAPACITOR_HTTPPOST_0_URL = "http://example.com/path"
> KAPACITOR_HTTPPOST_0_HEADERS_Example1 = "header1"
> KAPACITOR_HTTPPOST_0_HEADERS_Example2 = "header2"

https://docs.influxdata.com/kapacitor/v1.5/event_handlers/post/#configuring-and-using-multiple-http-post-endpoints

> Multiple HTTP POST endpoint configurations can also be added using environment variables. > 
> Variables values are grouped together using the number in each variable key.
>
> ```
> KAPACITOR_HTTPPOST_0_ENDPOINT = "example0"
> KAPACITOR_HTTPPOST_0_URL = "http://example-0.com/path"
> KAPACITOR_HTTPPOST_0_HEADERS_Example1 = "header1"
> KAPACITOR_HTTPPOST_0_HEADERS_Example2 = "header2"
> 
> KAPACITOR_HTTPPOST_1_ENDPOINT = "example1"
> KAPACITOR_HTTPPOST_1_URL = "http://example-1.com/path"
> KAPACITOR_HTTPPOST_1_HEADERS_Example1 = "header1"
> KAPACITOR_HTTPPOST_1_HEADERS_Example2 = "header2"
> ```

and others. However from my experience it the headers won't get added though they have been as enviromentment variables *while ENDPOINT AND URL*  work just fine.

## Example:

```
KAPACITOR_HTTPPOST_0_ENDPOINT = "example0"
KAPACITOR_HTTPPOST_0_URL = "http://example-0.com/path"
KAPACITOR_HTTPPOST_0_HEADERS_Example1 = "header1"
```

TickScript:

```js
|foo
   .httpPost()
   .endpoint('example0')
```

### Excepted:

- Header "Example1" is added

### Actual

- Header "Example1" is _not_ added

## Example 2:

Writing the header inline

```
KAPACITOR_HTTPPOST_0_ENDPOINT = "example0"
KAPACITOR_HTTPPOST_0_URL = "http://example-0.com/path"
```

TickScript:

```js
|foo
   .httpPost()
   .header('Example1', 'header1')
   .endpoint('example0')
```

### Excepted

- Header gets correctly added

### Actual

- Header gets correctly added

## Alternatives tried

- Also tried things like `KAPACITOR_HTTPPOST_0_HEADERS_0_Example1` and similar but those work don't either.

**Comment by russorat** [comment] 2020-02-12 04:50
@petetnt thanks for the issue. We will investigate if something was broken here.

**Comment by kramik1** [comment] 2021-02-26 19:24
I am running into this as well. I am trying to setup kapacitor in k8. I dumped the config that is in the container to see what it has set. The basic auth basic-auth settings might shine some light on the proper env variables. 

[[httppost]]
  ....
  [httppost.basic-auth]
    username = ""
    password = ""

**Comment by kramik1** [comment] 2021-02-27 22:56
OK, so kind of stupid on my part. But reading the toml docs (https://toml.io/en/v1.0.0#inline-table) made it super clear. 
Inline tables are only short hand for a new document section. So KAPACITOR_HTTPPOST_0_BASIC_AUTH_PASSWORD works. I am using a configmap for the conf file so that I do not have so many environmental variables and pulling the basic-auth password from a secret. Everything works as intended.

**Comment by docmerlin** [comment] 2022-01-21 17:35
closed by:, https://github.com/influxdata/kapacitor/pull/2653

**Closed by docmerlin** 2022-01-21 17:35 UTC
Labels: bug, pm/review
