### ISSUE TITLE
kapacitor processes duplicate messages

### ISSUE THREAD

**Issue by m4ce** [influxdata/kapacitor#1123] opened 2017-01-12 14:29 UTC
Hi,

I am having a weird issue with Kapacitor which seems to occur only when using stream without specifying any window.

I am writing a message at a time into Influx but when doing 'kapacitor show task', I always see two messages being processed.

This is my template tickscript:

```
            // Optional where filter
            var where_filter = lambda: "level" == 'ERROR'

            // Critical criteria
            var crit = lambda: TRUE

            // Dataframe
            var data = stream
                |from()
                    .measurement('app')
                    .where(where_filter)
                |eval(lambda: "message")
                    .as('message')
                    .tags('message')
                |groupBy('host', 'message')

            // Thresholds & Alerting
            data
                |alert()
                    .crit(crit)
                    .noRecoveries()
                    .message('[*{{ .Level }}*] App error - Host: {{ index .Tags "host" }}, Message: {{ index .Tags "message" }}')
                    .log('/tmp/app.log')
```

Because of two messages being processed, Kapacitor also generates two alerts as a result.

My understanding of the stream node without the use of window is that every tick will be handled as soon as it arrives. Is that a correct statement to make?

When looking into the alerts log, I find two alerts based on two identical messages processed.

**Comment by m4ce** [comment] 2017-01-12 16:40
Ignore this message, user error. The application was sending two messages at the same time.

It seems that when writing to Influx two identical messages (with the same timestamp), the point gets overwritten. As a result, Kapacitor will receive the new data point.

**Comment by m4ce** [comment] 2017-01-12 18:01
Actually, I was wrong again :(

The application was indeed sending unique messages. I tested against a new database in Influx and the issue disappeared. After switching back to original database the issue cropped up again.

After I deleted the database and re-created it, the issue has gone away!

**Comment by m4ce** [comment] 2017-01-12 18:33
Check this out:

```
kapacit ingress stats | grep 'test'
systems    default          test                                12
```

Send a new measurement (directly to Influx):

```
$ curl -i -XPOST 'http://localhost:8086/write?db=systems' --data-binary 'test,host=foo,level=ERROR message="bar"'
```

Check the ingress again:

```
# kapacitor stats ingress | grep test
systems    default          test                                15
```

My tickscript:

```
           // Optional where filter
            var where_filter = lambda: "level" == 'ERROR'

            // Critical criteria
            var crit = lambda: TRUE

            // Dataframe
            var data = stream
                |from()
                    .measurement('test')
                    .where(where_filter)
                |eval(lambda: "message")
                    .as('message')
                    .tags('message')
                |groupBy('host', 'message')

            // Thresholds & Alerting
            var alert = data
                |alert()
                    .crit(crit)
                    .noRecoveries()
                    .message('[*{{ .Level }}*] Test error - Host: {{ index .Tags "host" }}, Message: {{ index .Tags "message" }}')
                    .log('/tmp/test.log')
```

I've created the task as follows:

```
kapacitor define alert_test -dbrp systems.default -tick test.tick -type stream
```

**Comment by rossmcdonald** [comment] 2017-01-12 19:15
@m4ce This is with OSS InfluxDB, correct? Or is this against a cluster?

**Comment by m4ce** [comment] 2017-01-12 19:17
@rossmcdonald, yes this is with the OSS version, hence single instance

**Comment by nathanielc** [comment] 2017-01-12 19:48
@m4ce Can you try writing directly to Kapacitor to see if the issue is with the InfluxDB subscriptions? i.e.

```
curl -i -XPOST 'http://localhost:90902/write?db=systems&rp=default' --data-binary 'test,host=foo,level=ERROR message="bar"'
```

**Comment by m4ce** [comment] 2017-01-12 19:57
@nathanielc, it only increases by one when I go through kapacitor.. so yes it's the InfluxDB subscription :(

**Comment by m4ce** [comment] 2017-01-12 20:10
Hm, I may know now what's going on..

If I run 'show subscriptions' in InfluxDB, it returns 3 subscriptions to 'systems'.'default' all having different random names.

Not sure why Kapacitor is spawning three subscriptions? Could they be leftovers from previous runs?

**Comment by m4ce** [comment] 2017-01-12 20:56
Okay, I can confirm it was due to the multiple subscriptions (they all had different cluster ids). I guess it was due to previous tests/runs.

I only noticed that when Kapacitor shut downs it doesn't remove the subscriptions. However, not sure if that is by design?

**Comment by nathanielc** [comment] 2017-01-12 23:27
@m4ce OK, glad you figured it out. I'll close this for now.

**Closed by nathanielc** 2017-01-12 23:27 UTC

**Comment by jamischarles** [comment] 2017-12-01 04:03
I ran into this issue as well with the docker stack. I found a workaround. https://community.influxdata.com/t/replay-recording-shows-data-7x-instead-of-1x/3246
