### ISSUE TITLE
Task stops executing for no apparent reason

### ISSUE THREAD

**Issue by TeosVerdi** [influxdata/kapacitor#1020] opened 2016-11-07 09:58 UTC
Hello everyone, i'm using Telegraf+Kapacitor to alert when machines get high cpu usage. 
Linux and macOS readings work and alert fine, but the Kapacitor task i built for Windows machines fails for no apparent reason, while having the same structure. 
Please, help me find the culprit. 
**komaru.tick** (Template)
```
// Measurement to go thru
var measurement string
// Where filter
var where_filt = lambda: TRUE
// Grouping
var groups = [*]
// Window interval
var windowPeriod = 5m
var windowEvery = 5m
// The mean value
var medianField = ''
// Warning criteria, as lambda
var warning = lambda: FALSE
// Critical criteria, has access to 'mean' field
var critical lambda
// Telegram chat id
var chatid = ''
// Message to send
var message = '{{ .Level }}: {{ index .Fields "host"}}'

stream
	|from()
		.measurement(measurement)
		.where(where_filt)
		.groupBy(groups)
	|window()
		.period(windowPeriod)
		.every(windowEvery)
	|median(medianField)
		.as(medianField)
	|alert()
		.message(message)
		.warn(warning)
		.crit(critical)
		.stateChangesOnly()
		.telegram()
			.chatId(chatid)
```
**wincpu.json** (Windows alert, which doesn't work)
```
{
    "measurement": {"type" : "string", "value" : "win_cpu" },
    "groups": {"type": "list", "value": [{"type":"string", "value":"host"}]},
    "warning": {"type" : "lambda", "value" : "\"Percent_Processor_Time\" > 75.0" },
    "critical": {"type" : "lambda", "value" : "\"Percent_Processor_Time\" > 90.0" },
    "message": {"type": "string", "value": "{{ .Level }}: CPU has {{ index .Fields \"Percent_Processor_Time\" | printf \"%0.2f\" }}% of user usage on {{ index .Tags \"host\" }}"},
    "windowPeriod": {"type" : "duration", "value" : "5m" },
    "windowEvery": {"type" : "duration", "value" : "1m" },
    "medianField": {"type": "string", "value": "Percent_Processor_Time"}
}
```
**cpu.json** (Linux/OSX alert, which works fine)
```
{
    "measurement": {"type" : "string", "value" : "cpu" },
    "groups": {"type": "list", "value": [{"type":"string", "value":"host"}]},
    "warning": {"type" : "lambda", "value" : "\"usage_user\" > 75.0" },
    "critical": {"type" : "lambda", "value" : "\"usage_user\" > 90.0" },
    "message": {"type": "string", "value": "{{ .Level }}: CPU has {{ index .Fields \"usage_user\" | printf \"%0.2f\" }}% of user usage on {{ index .Tags \"host\" }}"},
    "windowPeriod": {"type" : "duration", "value" : "5m" },
    "windowEvery": {"type" : "duration", "value" : "1m" },
    "medianField": {"type": "string", "value": "usage_user"}
}
```
syslog failure message
```
Nov  7 12:43:42 kapacitord[7544]: [wincpu_alert:median3] 2016/11/07 12:43:42 E! invalid influxql func median with field Percent_Processor_Time: invalid field type: <nil>
Nov  7 12:43:42 kapacitord[7544]: [task_master:main] 2016/11/07 12:43:42 E! Stopped task: wincpu_alert median3: invalid influxql func median with field Percent_Processor_Time: invalid field type: <nil>
Nov  7 12:43:42 kapacitord[7544]: [task_store] 2016/11/07 12:43:42 E! task wincpu_alert finished with error: median3: invalid influxql func median with field Percent_Processor_Time: invalid field type: <nil>
```
Kapacitor ver. 1.0.2, pre-built.

**Comment by rossmcdonald** [comment] 2016-11-07 16:04
The error:

```
invalid field type: <nil>
```

Means that Kapacitor received a null value for the `Percent_Processor_Time` field. Are you sure the field is being sent with the Telegraf data? You can use a `|log()` node to have the task print out the data being received.

To get rid of the error message, you can use a `|default()` node to default that field to a value, but you might want to verify the data being sent by Telegraf.

**Comment by rossmcdonald** [comment] 2016-11-10 15:49
@TeosVerdi Does using `default` fix the issue? Or were you able to determine the cause of the problem?

**Comment by docmerlin** [comment] 2020-08-28 18:19
I'm going to go ahead and close this as @TeosVerdi hasn't responded and it has been 4 years.

**Closed by docmerlin** 2020-08-28 18:19 UTC
